# Generated by Django 4.2.5 on 2023-10-03 14:25

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year_established', models.DateField()),
                ('brief_history', models.TextField()),
                ('diocesan_overview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diocese_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YouthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youth_groups', to='diocese.diocese')),
            ],
        ),
        migrations.CreateModel(
            name='YouthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='diocese.youthgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('ordination_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('congregation', models.CharField(choices=[('CARMELITE FRIARS', 'Carmelite Friars'), ('CLARETIAN FATHERS', 'Claretian Fathers'), ('DEI VERBUM', 'Dei Verbum'), ('DIOCESAN PRIEST', 'Diocesan Priest'), ('DOMINICIAN FATHERS', 'Dominician Fathers'), ('FRANCISCAN FRIARS (CAPUCHINS)', 'Franciscan Friars (Capuchins)'), ('HOLY GHOST FATHERS', 'Holy Ghost Fathers'), ('MISSIONARIES OF AFRICA', 'Missionaries of Africa'), ('OBLATES OF JOSEPH', 'Oblates of Joseph'), ('OBLATES OF THE BLESSED VIRGIN MARY', 'Oblates of the Blessed Virgin Mary'), ('OPUS DEI', 'Opus Dei'), ('ST. JOSEPH’S SOCIETY OF THE SACRED HEART', 'St. Joseph’s Society of the Sacred Heart'), ('SONS OF MARY MOTHER MERCY', 'Sons of Mary Mother Mercy'), ('SOCIETY OF ST. PAUL', 'Society of St. Paul'), ('SCHOENSTATT FATHERS', 'Schoenstatt Fathers'), ('SALESIANS FATHERS', 'Salesians Fathers'), ('REDEMPTORIST COMMUNITY', 'Redemptorist Community'), ('SERVANT OF CHARITY', 'Servant of Charity'), ('SMA REGIONAL HOUSE', 'SMA Regional House'), ('SOCIETY OF DIVINE VOCATION (SDV)', 'Society of Divine Vocation (SDV)')], default='DIOCESAN PRIEST', max_length=50)),
                ('parishes', models.ManyToManyField(related_name='assigned_priests', to='diocese.parish')),
            ],
        ),
        migrations.AddField(
            model_name='parish',
            name='clergy',
            field=models.ManyToManyField(related_name='parish_assignments', to='diocese.priest'),
        ),
        migrations.AddField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parishes', to='diocese.diocese'),
        ),
        migrations.CreateModel(
            name='MassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('chapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_schedules', to='diocese.chapel')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], default='FEMALE', max_length=13)),
                ('date_of_birth', models.DateField()),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('user_type', models.CharField(choices=[('admin', 'ADMIN'), ('editor', 'EDITOR')], default='EDITOR', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chapel',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapels', to='diocese.diocese'),
        ),
        migrations.CreateModel(
            name='Bishop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ordination_date', models.DateField()),
                ('biographhy', models.TextField()),
                ('congregation', models.CharField(choices=[('CARMELITE FRIARS', 'Carmelite Friars'), ('CLARETIAN FATHERS', 'Claretian Fathers'), ('DEI VERBUM', 'Dei Verbum'), ('DIOCESAN PRIEST', 'Diocesan Priest'), ('DOMINICIAN FATHERS', 'Dominician Fathers'), ('FRANCISCAN FRIARS (CAPUCHINS)', 'Franciscan Friars (Capuchins)'), ('HOLY GHOST FATHERS', 'Holy Ghost Fathers'), ('MISSIONARIES OF AFRICA', 'Missionaries of Africa'), ('OBLATES OF JOSEPH', 'Oblates of Joseph'), ('OBLATES OF THE BLESSED VIRGIN MARY', 'Oblates of the Blessed Virgin Mary'), ('OPUS DEI', 'Opus Dei'), ('ST. JOSEPH’S SOCIETY OF THE SACRED HEART', 'St. Joseph’s Society of the Sacred Heart'), ('SONS OF MARY MOTHER MERCY', 'Sons of Mary Mother Mercy'), ('SOCIETY OF ST. PAUL', 'Society of St. Paul'), ('SCHOENSTATT FATHERS', 'Schoenstatt Fathers'), ('SALESIANS FATHERS', 'Salesians Fathers'), ('REDEMPTORIST COMMUNITY', 'Redemptorist Community'), ('SERVANT OF CHARITY', 'Servant of Charity'), ('SMA REGIONAL HOUSE', 'SMA Regional House'), ('SOCIETY OF DIVINE VOCATION (SDV)', 'Society of Divine Vocation (SDV)')], default='DIOCESAN PRIEST', max_length=50)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_bishops', to='diocese.diocese')),
            ],
        ),
    ]
